### ISSUE TITLE
ChrisChoTW ubike search

### ISSUE THREAD

**Issue by ChrisChoTW** [kurotanshi/vue-ubike-information#10]
Page: https://chrischotw.github.io/ubike-information/
Github: https://github.com/ChrisChoTW/ChrisChoTW.github.io

主題：Ubike資訊搜尋
特點：
1.可自由選擇想要查看的欄位
2.可對站名、地址、區域等進行中英文的查詢
3.提供正規表示法的查詢給進階的使用者
4.對於場地總數、目前空位數、目前停放數分別設定數值搜尋
5.文字及車輛數的查詢可進行交集或是聯集
6.對於查詢後的結果加上突出顯示的效果
 
Thank you.

**Comment by kurotanshi** [comment]
整體來說，加入的都是些很實用的功能，很棒。

有個部分不知道是不是我上次沒提到，在 `input` 表單內，如果 `v-model` 對應的屬性是一樣的話，那個 `input` 裡面的 `name` 是可以省略不寫的。

再來，雖然跟 vue.js 無關，在這個 case 裡面用 `eval( )` 寫很爽，尤其像在拼湊 expression 這種的情況。 但基於性能和安全上的考量，可以少用還是盡量避免。

遇到這類情況，通常我會另外寫個 method 來處理：
```
function compare(a, op, b) {
  switch (op) {
    case '>': return a > b;
    case '<': return a < b;
    case '===': return a === b;
   // 後略
  }
}
```
類似這樣的方式來處理，可以避免 `eval( )` 帶來非必要的麻煩。

有實做 RegExp 這點很棒， Good Job!
