### ISSUE TITLE
改用data.taipei卻遇到CORS的問題

### ISSUE THREAD

**Issue by yoyoys** [kurotanshi/vue-ubike-information#2]
老師提供的API工作正常：https://tcgbusfs.blob.core.windows.net/blobyoubike/YouBikeTP.gz
照台北市API官方的建議，改用官方的界接平台
我採用的是這組：
http://data.taipei/opendata/datalist/apiAccess?scope=resourceAquire&rid=ddb80380-f1b3-4f8e-8016-7ed9cba571d5
另外一組也試過了：http://data.taipei/youbike
試過兩組都遇到CORS的問題，顯然是伺服器設定阻擋這個要求。

雖說用第一組API就沒問題了，但還是很想問
data.taipei本身為什麼要阻擋cors的呼叫？不是公共API嗎？
還是說這是By Design？

謝謝

**Comment by kurotanshi** [comment]
其實 data.taipei 提供的多數 API 預設是沒有開放 CORS 的
後來經詢問後才有部分與交通有關的即時 open data API 開啟 CORS

可參考這個頁面 https://taipeicity.github.io/traffic_realtime/
