### ISSUE TITLE
Hi Kuro, 我來交作業囉！

### ISSUE THREAD

**Issue by mvpdw06** [kurotanshi/vue-ubike-information#6]
## Demo
https://mvpdw06.github.io/vue-ubike-information/

## Source Code
https://github.com/mvpdw06/vue-ubike-information

Thanks!

**Comment by kurotanshi** [comment]
網站的功能相當完整，程式架構也相當不錯。

真要雞蛋裡挑骨頭的話，大概就是每 30 秒重整資料的時候，原本資料排序的部分會被 reset，這類的小細節。 但也無傷大雅。

比較可惜的是，另開視窗的地圖沒有把站點名稱帶出去，開多了會不知道這是哪裡，但這是 Google 的問題。 如果可以用 Google map API 去建立地圖的話，使用者體驗會更好。 😃
