### ISSUE TITLE
嗨，我的作業在這邊

### ISSUE THREAD

**Issue by yoyoys** [kurotanshi/vue-ubike-information#7]
## Demo
* https://yoyoys.github.io/vue-ubike-information/
## YouBike 臺北市公共自行車即時資訊
* 按照自己喜好選擇分類方式
* 動態載入行政區
* 站點更新通知功能
* 站點更新時會產生動畫，並且出現提示訊息
* 點擊站點名稱可以切換至該站點

## 註解
* 經測試，官方API應該是五分鐘才刷新一次，為了顯示效果就改為五秒更新一次
* 如想要測試可以在console中輸入 `vm.stationDic.s0001.sbi='123'` 或你喜歡的數值和站點

**Comment by yoyoys** [comment]
忘記附上原始碼了  sorry

https://github.com/yoyoys/vue-ubike-information

**Comment by kurotanshi** [comment]
就功能面來說，建議「控制與顯示列表的區塊」預設可以開啟，沒開啟的狀況下不容易理解這個地圖一開始要做什麼。

另外，透過字串長度做分組的方式也相當特別，感覺比較像是分析某行政區的站點數/停車格。
如果可以做到點擊 marker 反查該站點的狀態，會比較符合一般使用者的操作習慣。

站點更新通知的功能很不錯，如果可以做到過濾某個條件，只觀察符合條件下的狀態更新 (如使用者挑選某個行政區後，只顯示該行政區的站點更新) 就更好了。

程式的架構部分，我看見你有用到 toastr JS 這個 notifications plugin，在下次的課程中會講到 Vue component (元件/組件)，建議之後可以試著將這類的 plugin 拆出至另外一個 component，可以降低功能之間的耦合度。 😃

**Comment by yoyoys** [comment]
謝謝老師~順便說一下我遇到的難處。

1. 關於關閉選單
    其實一開始關閉的原因是對Google Map API不夠熟悉，我設定成一開始就開啟的話，他只會cache一開始render出來的那個區塊，我想應該有什麼viewport的屬性可以設定，但還不太熟。

2. 字串長度做分組的原因
   其實是按照欄位分組的功能做出來之後發現只有行政區域這個選項有用，其他都一點用都沒有，所以就做出來當雞肋一下，無奈

**Comment by kurotanshi** [comment]
地圖與選單的部分應是 CSS 互相擠壓造成的結果，你可在 #map 加上 position: absolute; 與  z-index: 0; ，再試著將 isDrawerOpen 改成預設開啟 `isDrawerOpen: true` 應該就能解決這問題。

``` css
#map {
    position: absolute;
    width: 100%;
    height: 100vh;
    margin-right: 4%;
    z-index: 0;
}
```
